FROM nginx:1.26-alpine

COPY frontend/dist /usr/share/nginx/html
COPY whatsapp-plugin/dist /usr/share/nginx/html/whatsapp-plugin
COPY deploy/docker-compose/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080
